<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMsJ5zch\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMsJ5zch/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMsJ5zch.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMsJ5zch\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMsJ5zch\App_KernelDevDebugContainer([
    'container.build_hash' => 'MsJ5zch',
    'container.build_id' => 'b6e4d4b2',
    'container.build_time' => 1630941233,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMsJ5zch');
